        <div class="nav-bar">
            <nav>
                <div class="logo">
                    <a href="index.php"><img src="images/main_logo.jpg" alt="main logo"></a>
                </div>
            
                <input type="checkbox" id="check">
                <label for="check" class="checkopen">
                    <i class="fa-solid fa-bars" id="open"></i>
                    <i class="fa-solid fa-times" id="close"></i>
                </label>
                <ul>
                    <li><a href="index.php"><i class="fa-solid fa-house"></i>&nbsp;Home</a></li>
                    <li><a href="about.php"><i class="fa-solid fa-users"></i>&nbsp;About</a></li>
                    <li><a href="jobs.php"><i class="fa-solid fa-truck-plane"></i>&nbsp;Career</a></li>
                    <li><a href="apply.php"><i class="fa-solid fa-address-card"></i>&nbsp;Apply</a></li>
                    <li><a href="enhancements.php"><i class="fa-solid fa-star"></i>&nbsp;Enhancement</a></li>
                    <li><a href="manage.php"><i class="fa-solid fa-user"></i>&nbsp;Manage</a></li>
                    <li>
                </ul>
            </nav>
        </div>